FROM python:3.11-slim

WORKDIR /app

# Dependências do sistema
RUN apt-get update && \
    apt-get install -y gcc libffi-dev libpq-dev curl netcat-traditional && \
    rm -rf /var/lib/apt/lists/*

# Instala as dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante da aplicação
COPY . .

# Adiciona o diretório app ao PYTHONPATH
ENV PYTHONPATH=/app

# Expor a porta do FastAPI
EXPOSE 8000

# Script de inicialização para rodar o FastAPI e o Celery worker
COPY start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/start.sh"]
